### PR TITLE
Create screen register

### PR DESCRIPTION
**Pull request by DungKM**
- Xây dựng UI Register
- Xử lý logic 
- Fetch API 
- Validate Register

### CODE REVIEW

**Comment by DungKM** [comment]
Code đã oke

**Review by Manhnd10803 — COMMENTED** [review]
Ngon

**Review by Manhnd10803 — APPROVED** [review]
Code ok

**Comment by Phan-Luan** [comment]
code ok

**Review by Phan-Luan — APPROVED** [review]
code oke

**Review by mhfed — APPROVED** [review]
code ok

**Review by lehong050503 — APPROVED** [review]
Ok

**Pull request merged**
