### PR TITLE
Create forgot password and view question and answer

### PR DESCRIPTION
**Pull request by lehong050503**
Forgot Password and View Question and Answer

### CODE REVIEW

**Review by Manhnd10803 — DISMISSED** [review]
Sịn

**Comment by DungKM** [comment]
Bạn làm rất tốt

**Review by DungKM — DISMISSED** [review]
code oke

**Review by Phan-Luan — DISMISSED** [review]
code sịn

**Comment by mhfed** [comment]
ok

**Comment by mhfed** [comment]
ok

**Review by mhfed — APPROVED** [review]
sịn

**Review by DungKM — APPROVED** [review]
rất tốt

**Review by Phan-Luan — APPROVED** [review]
code okee

**Review by Manhnd10803 — APPROVED** [review]
Ngon

**Pull request merged**
